import { BillingAddress } from '@/models/Order';
import { ProductData } from '@/models/Product/Product';

export const mockSimpleProductData: ProductData = {
    id: 101,
    name: 'Simple Test Product',
    price: 100,
    regular_price: 100,
    sale_price: 0,
    on_sale: false,
    featured: false,
    stock_status: 'instock',
    description: 'A simple product for testing.',
    short_description: 'Simple test product.',
    categories: [],
    images: [],
    attributes: [],
    variations: [],
    related_ids: [],
    type: 'simple',
    default_attributes: [],
    parent_id: 0,
};

export const mockVariableProductData: ProductData = {
    id: 202,
    name: 'Variable Test Product',
    price: 0,
    regular_price: 0,
    sale_price: 0,
    on_sale: false,
    featured: false,
    stock_status: 'instock',
    description: 'A variable product for testing.',
    short_description: 'Variable test product.',
    categories: [],
    images: [],
    attributes: [{ id: 1, name: 'Color', options: ['Red', 'Blue'], variation: true, visible: true }],
    variations: [203, 204],
    related_ids: [],
    type: 'variable',
    default_attributes: [],
    parent_id: 0,
};

export const mockVariation1Data: ProductData = {
    id: 203,
    name: 'Variable Test Product - Red',
    price: 150,
    regular_price: 150,
    sale_price: 0,
    on_sale: false,
    featured: false,
    stock_status: 'instock',
    description: 'Red variation.',
    short_description: 'Red variation.',
    categories: [],
    images: [],
    attributes: [{ id: 1, name: 'Color', option: 'Red', variation: true, visible: true }],
    variations: [],
    related_ids: [],
    type: 'variation',
    default_attributes: [],
    parent_id: 202,
};

export const mockVariation2Data: ProductData = {
    id: 204,
    name: 'Variable Test Product - Blue',
    price: 160,
    regular_price: 160,
    sale_price: 0,
    on_sale: false,
    featured: false,
    stock_status: 'instock',
    description: 'Blue variation.',
    short_description: 'Blue variation.',
    categories: [],
    images: [],
    attributes: [{ id: 1, name: 'Color', option: 'Blue', variation: true, visible: true }],
    variations: [],
    related_ids: [],
    type: 'variation',
    default_attributes: [],
    parent_id: 202,
};

export const mockAddress: BillingAddress = {
    first_name: 'Test',
    last_name: 'User',
    address_1: '123 Test Street',
    address_2: 'Apt 4B',
    city: 'Testville',
    state: 'Testland',
    postcode: '12345',
    country: 'NO',
    email: 'test.user@example.com',
    phone: '12345678',
};
