/**
 * This file contains mock data for API responses, useful for testing and development.
 */

// A sample successful response from posting a new order to the WooCommerce API.
export const mockSuccessfulOrderResponse = {
    "_links": {
        "collection": [{}],
        "email_templates": [{}],
        "self": [{}]
    },
    "billing": {
        "address_1": "123 Test Street",
        "address_2": "Apt 4B",
        "city": "Testville",
        "company": "",
        "country": "NO",
        "email": "test.user@example.com",
        "first_name": "Test",
        "last_name": "User",
        "phone": "12345678",
        "postcode": "12345",
        "state": "Testland"
    },
    "cart_hash": "",
    "cart_tax": "0.00",
    "coupon_lines": [],
    "created_via": "rest-api",
    "currency": "NOK",
    "currency_symbol": "kr",
    "customer_id": 0,
    "customer_ip_address": "",
    "customer_note": "",
    "customer_user_agent": "",
    "date_completed": null,
    "date_completed_gmt": null,
    "date_created": "2025-07-25T20:20:16",
    "date_created_gmt": "2025-07-25T19:20:16",
    "date_modified": "2025-07-25T20:20:18",
    "date_modified_gmt": "2025-07-25T19:20:18",
    "date_paid": null,
    "date_paid_gmt": null,
    "discount_tax": "0.00",
    "discount_total": "0.00",
    "fee_lines": [],
    "id": 248238,
    "is_editable": true,
    "line_items": [
        {
            "id": 39091,
            "image": {},
            "meta_data": [],
            "name": "",
            "parent_name": null,
            "price": 0,
            "product_id": 0,
            "quantity": 1,
            "sku": null,
            "subtotal": "0.00",
            "subtotal_tax": "0.00",
            "tax_class": "",
            "taxes": [],
            "total": "0.00",
            "total_tax": "0.00",
            "variation_id": 0
        },
        {
            "id": 39092,
            "image": {},
            "meta_data": [],
            "name": "",
            "parent_name": null,
            "price": 0,
            "product_id": 0,
            "quantity": 1,
            "sku": null,
            "subtotal": "0.00",
            "subtotal_tax": "0.00",
            "tax_class": "",
            "taxes": [],
            "total": "0.00",
            "total_tax": "0.00",
            "variation_id": 0
        }
    ],
    "meta_data": [],
    "needs_payment": false,
    "needs_processing": false,
    "number": "248238",
    "order_key": "wc_order_NUhs6DXWrq7qa",
    "parent_id": 0,
    "payment_method": "svea_checkout",
    "payment_method_title": "",
    "payment_url": "https://hunde-sport.no/kassen/order-pay/248238/?pay_for_order=true&key=wc_order_NUhs6DXWrq7qa",
    "prices_include_tax": true,
    "refunds": [],
    "shipping": {
        "address_1": "123 Test Street",
        "address_2": "Apt 4B",
        "city": "Testville",
        "company": "",
        "country": "NO",
        "first_name": "Test",
        "last_name": "User",
        "phone": "12345678",
        "postcode": "12345",
        "state": "Testland"
    },
    "shipping_lines": [],
    "shipping_tax": "0.00",
    "shipping_total": "0.00",
    "status": "pending",
    "tax_lines": [
        {
            "compound": false,
            "id": 39093,
            "label": "MVA",
            "meta_data": [],
            "rate_code": "NO-MVA-1",
            "rate_id": 1,
            "rate_percent": 25,
            "shipping_tax_total": "0.00",
            "tax_total": "0.00"
        }
    ],
    "total": "0.00",
    "total_tax": "0.00",
    "transaction_id": "",
    "version": "10.0.4"
};
